//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


[XmlRoot("services")]
public partial class ChirchServices {
    
    private timetable[] timetableServicesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("service")]
    public timetable[] TimetableServices {
        get {
            return this.timetableServicesField;
        }
        set {
            this.timetableServicesField = value;
        }
    }
}


public partial class timetable {
    
    private System.DateTime dateField;
    
    private string megadescriptionField;
    
    private System.DateTime timeField;
    
    private string eventdesciptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string megadescription {
        get {
            return this.megadescriptionField;
        }
        set {
            this.megadescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time")]
    public System.DateTime time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string eventdesciption {
        get {
            return this.eventdesciptionField;
        }
        set {
            this.eventdesciptionField = value;
        }
    }
}
